name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'   # Compatible with most plugins

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-include-markdown-plugin
          pip install mkdocs-jupyter
          pip install pymdown-extensions
          pip install mkdocs-exclude
          # pip install mkdocs-tags-plugin  # Optional

      - name: Build and deploy
        run: mkdocs gh-deploy --force
